[package]
name = "sql-generate"
version = "0.1.0"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.5"


[[bin]]
name = "realrun"
path = "src/realrun.rs"